"""Cross-implementation parity tests.

Asserts our Python implementation produces byte-identical output to viem
(the canonical JS reference used by chain-tools and erc8213.eth.limo) for
calldata digests and EIP-712 typed-data hashes.

Vectors live in `tests/fixtures/parity_vectors.json` and are regenerated by
running `node tests/fixtures/generate_parity_vectors.mjs` from inside the
chain-tools repo (which has viem installed).
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from clearsig._calldata_digest import calldata_digest_hex
from clearsig._eip712 import hash_domain, hash_message, hash_typed_data

_VECTORS_PATH = Path(__file__).parent.parent / "fixtures" / "parity_vectors.json"


def _load() -> dict:
    return json.loads(_VECTORS_PATH.read_text())


_VECTORS = _load()


class TestCalldataDigestParityWithViem:
    """Every viem-computed digest must match ours byte-for-byte."""

    @pytest.mark.parametrize(
        "case",
        _VECTORS["calldataDigest"],
        ids=lambda c: c["label"],
    )
    def test_matches_viem(self, case: dict) -> None:
        assert calldata_digest_hex(case["input"]) == case["digest"]


class TestEip712ParityWithViem:
    """Every viem-computed EIP-712 hash must match ours byte-for-byte."""

    @pytest.mark.parametrize(
        "case",
        _VECTORS["eip712"],
        ids=lambda c: c["label"],
    )
    def test_domain_matches_viem(self, case: dict) -> None:
        assert "0x" + hash_domain(case["doc"]).hex() == case["domainHash"]

    @pytest.mark.parametrize(
        "case",
        _VECTORS["eip712"],
        ids=lambda c: c["label"],
    )
    def test_message_matches_viem(self, case: dict) -> None:
        assert "0x" + hash_message(case["doc"]).hex() == case["messageHash"]

    @pytest.mark.parametrize(
        "case",
        _VECTORS["eip712"],
        ids=lambda c: c["label"],
    )
    def test_digest_matches_viem(self, case: dict) -> None:
        assert "0x" + hash_typed_data(case["doc"]).hex() == case["digest"]
